name: Manually Triggered Workflow
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      environment:
        description: 'Environment to deploy'
        required: false
        default: 'staging'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Podman
        run: |
          sudo apt update
          sudo apt-get -y install podman
      - name: Pull image
        run: sudo podman pull ghcr.io/quiet-inventor/bootc-example:latest
